{% set name = "dvc-objects" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb0101e3e942f3eb648d4a10448b92c30616f4fdd6c626bc1397761b18e98d02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - nanotime >=0.5.2
    - funcy >=1.14
    - shortuuid >=0.5.0
    - tqdm >=4.63.1,<5
    - flatten-dict >=0.4.1,<1
    - typing_extensions >=3.7.4
    - fsspec >=2021.10.1
    - diskcache >=5.2.1

test:
  imports:
    - dvc_objects
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-objects
  summary: Library for generic objects used in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
