{% set name = "dvc-objects" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59752fd9d8af9e81b389e57a5aac5b9b14097e63be4969bd50dfde4119144ada

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - funcy >=1.14
    - shortuuid >=0.5.0
    - tqdm >=4.63.1,<5
    - typing_extensions >=3.7.4
    - fsspec >=2021.10.1

test:
  imports:
    - dvc_objects
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-objects
  summary: Library for generic objects used in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
